# Generated by Django 4.1 on 2022-09-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="first_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="一面面试官",
            ),
        ),
    ]
